### ISSUE TITLE
Failed to lookup symbol 'readBarcode'

### ISSUE THREAD

**Issue by om-ha** [khoren93/flutter_zxing#77]
This issue exists in latest commit (4ebc637dfb3208f72c9c8adda813e1f58d3ed99a) and not version 0.10.0

# 1. Underlying Exception
### Path
/Users/user/.pub-cache/git/flutter_zxing-4ebc637dfb3208f72c9c8adda813e1f58d3ed99a/lib/generated_bindings.dart

### Exception
Exception has occurred.
ArgumentError (Invalid argument(s): Failed to lookup symbol 'readBarcode': dlsym(RTLD_DEFAULT, readBarcode): symbol not found)

### Offending code
```dart
late final _readBarcodePtr = _lookup<
      ffi.NativeFunction<
          CodeResult Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int, ffi.Int,
              ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.Int)>>('readBarcode');
// ---------------------------------------------------------^
```

# 2. User-Facing Exception
### Path
/Users/user/.pub-cache/git/flutter_zxing-4ebc637dfb3208f72c9c8adda813e1f58d3ed99a/lib/zxing_mobile.dart

### Exception
Exception has occurred.
_CastError (type 'ArgumentError' is not a subtype of type 'Code' in type cast)

### Offending code
```dart
await zxingProcessCameraImage(image, params: params) as Code;
// --------------------------------------------------^
```

# 3. Usage
### Init / Dispose 
```dart
// StatefulWidget state property
final Zxing zxMobile = ZxingMobile();

// called from initState
await zxMobile.startCameraProcessing();

// called inside dispose
zxMobile.stopCameraProcessing();
```
### processCameraImage
```dart
// `CameraImage` object comes from `startImageStream` from `camera` package
// https://github.com/flutter/plugins/blob/729c14a9243ebd2b16d7ec2a63b4e54661b00641/packages/camera/camera/lib/src/camera_controller.dart#L415
Code zxBarcode = await zxMobile.processCameraImage(
    cameraImage,
    params: DecodeParams(
        tryHarder: false,
        tryRotate: true,
        tryInverted: false,
    ),
);
```

# 4. pubspec.yaml
## offending versions
```yaml
flutter_zxing:
  git:
    url: https://github.com/khoren93/flutter_zxing.git
    ref: 4ebc637dfb3208f72c9c8adda813e1f58d3ed99a
```

## working pubspec.yaml
```yaml
flutter_zxing: 0.10.0
```

# Platform Information
- iOS
```
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (9 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
```

**Comment by om-ha** [comment]
Another question if you may, which one is more recommended when using flutter_zxing with camera package?
- `processCameraImage` (parameter is `CameraImage`)
- `readBarcode` (parameter is image bytes `InputImage` -> byte list property `Uint8List?`)

**Comment by khoren93** [comment]
Thanks for reaching out.

Since version 1.0.0, the flutter_zxing package uses submodules, so specifying a specific version in the pubspec file is not possible. To use the main branch, you will need to manually clone it locally using the command "git clone --recursive https://github.com/khoren93/flutter_zxing.git". Once the package is cloned, navigate to the "scripts" directory using "cd scripts" and run the script "sh update_ios_macos_src.sh". After this, you can add the flutter_zxing package as a local dependency in the pubspec file by specifying the path of the cloned local repository. For example, if you cloned the package in your home directory, the path would be 
```
flutter_zxing: 
  path: ~/flutter_zxing
```

For the second question, it is highly recommended to use the processCameraImage method, rather than the readBarcode method. The reason for this is that processCameraImage is specifically designed to work with the camera stream, and it processes the stream in a separate isolate. This allows for more efficient and reliable barcode scanning, as well as improved performance and reduced memory usage. However, the readBarcode method can still be used to read barcodes from local image files, such as those from the gallery or from a URL. It takes as parameter InputImage which is a object with properties like bytes (Uint8List) and it's more appropriate for use with static images rather than a camera stream.

**Comment by khoren93** [comment]
Closing for now as this is already fixed.
